### PR TITLE
trying to see if upload broken

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
thanks @dnadeau4. Do you think we should still build 1.9 and 1.10 numpys?

**Comment by dnadeau4** [comment]
It is green now.  I reverted to:

 * wget https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh  -O miniconda.sh;

**Comment by doutriaux1** [comment]
Awesone! Thx Denis! Thx for reporting to conda as well!

**Comment by dnadeau4** [comment]
Everything is now working with conda_upload.sh for python3 and python2.  I tried to disable the codacy/pr but it got resurrected somehow.

**Comment by doutriaux1** [comment]
thanks @dnadeau4 I'll look into the codacy thing. It's going to prevent nightly uploads otherwise

**Comment by dnadeau4** [comment]
I just turned it off in my setting.  I think it was passed automatically.  I don't know why it did not happened before now.

**Comment by doutriaux1** [comment]
ok I think I turned it off

**Comment by doutriaux1** [comment]
ok we both did. 👍 we should be good.

**Pull request merged**
