### PR TITLE
Replace hard-coded character codes with np.dtype(...).char

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by doutriaux1** [comment]
hi @eric-wieser, thanks for this, would you mind adding a test for this to make sure nothing broke?
Thanks.

**Comment by eric-wieser** [comment]
Shouldn't existing tests tell you whether nothing broke?

**Comment by doutriaux1** [comment]
@eric-wieser it "should" be our coverage isn't so great, and one of our in-house requirement is to add a test to every PR (in order to solve slowly solve that) or point to a test that already checks it (although the idea is that if we bug fix then existing tests were incomplete)

**Comment by doutriaux1** [comment]
@dnadeau4 do you know if we have existing tests that cover this.

**Comment by dnadeau4** [comment]
@eric-wieser this code was written in the late 90's early 2000 probably in python 1.0, so no test was required at that time.   I looked at the numpy documentation and I don't see any deprecation for sctype2char.

I don't mind making the change and writing a test, but can you tell why you think this will be deprecated?

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.sctype2char.html?highlight=sctype2char#numpy.sctype2char

**Comment by eric-wieser** [comment]
I never said it will be deprecated - there's just no reason to use it over `dtype(t).char`.

**Comment by dnadeau4** [comment]
@eric-wieser is `dtype(t).char` better?  What is your rationale for the change then.

**Comment by eric-wieser** [comment]
If nothing else, right now it's pretty inconsistent using `sctype2char` in some places, but hard-coding character codes in others.

> What is your rationale for the change then.

I will probably propose deprecating it in the 1.17 release of numpy, and figured I'd give you a head start. While not something you care about here, it doesn't work on third-party dtypes, unlike `np.dtype(t).char` which does. This was the only project I could find using the function via github search or google.

**Comment by dnadeau4** [comment]
@eric-wieser Thanks! This is worth making the change.

**Pull request merged**
