### PR TITLE
Stop using the soon-to-be-deprecated np.int / np.float

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@eric-wieser same thing here, a test to make sure nothing was broken would nice.

**Comment by dnadeau4** [comment]
For this one, I read that this is "sort of deprecated"  I will make the necessary change, but I don't know how to test each case just yet. 😏

**Comment by eric-wieser** [comment]
I don't really see how there's anything to test here - it's just a dictionary mapping numpy names to your names. This is one of those things that can only really be checked by a human reading it.

Sure, you could write:

```python
CdToNumericType = {CdByte: numpy.byte}
```
```python
def test_cd_to_numeric_type():
   assert CdToNumericType[CdByte] == numpy.byte
```

But that's about as useful as writing:
```python
one = 1
```
```python
def test_one():
    assert one == 1
```

**Comment by eric-wieser** [comment]
> I read that this is "sort of deprecated"

I think the correct reading is "hard to deprecate" - we can't easily emit warnings until CPython 3.7

**Comment by dnadeau4** [comment]
@eric-wieser thanks,  I'll write the test just to add coverage percent.  😏

**Pull request merged**
