### PR TITLE
Update keys call in cdscan for Python 3

### LINKED ISSUE #397: AttributeError with cdscan
**Describe the bug**

cdscan failing with `AttributeError: 'dict_keys' object has no attribute 'append'`. This is affecting our ability to access a number of CESM files within CFMIP (since we are not able to produce xmls for the files). 

It seems this was documented before and there may be a fix ([here](https://github.com/CDAT/cdms/issues/256)). If you'd like, I can attempt a pull request with a fix. 

**To Reproduce**

`cdscan -x test.xml /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/*.nc`

**Environment (please complete the following information):**
 - OS: RHEL 7.8
 - CDAT8.2 / Python 3.7.3

**Related Issues**
- [Attribute error on cdscan](https://github.com/CDAT/cdms/issues/256)
- [cdscan error with Python 3](https://github.com/CDAT/cdms/issues/239)

**Error**

> $ cdscan -x test.xml /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/*.nc
> Finding common directory ...
> Common directory: /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/
> Scanning files ...
> /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/clisccp_CFmon_CESM2_amip-4xCO2_r1i1p1f1_gn_197901-201412.nc
> Traceback (most recent call last):
>   File "/export_backup/pochedley1/bin/anaconda3/envs/cdat82/bin/cdscan", line 1842, in <module>
>     main(sys.argv)
>   File "/export_backup/pochedley1/bin/anaconda3/envs/cdat82/bin/cdscan", line 1155, in main
>     varnames.append(axisvar.id)
> AttributeError: 'dict_keys' object has no attribute 'append'

### PR DESCRIPTION
**Pull request by forsyth2**
Update calls in cdscan for Python 3. Resolves #397.

### CODE REVIEW

**Comment by forsyth2** [comment]
@jasonb5 Ready for review. I wrote a script to check for any instances of `keys()`, `values()`, or `items()` not wrapped in `list` or in a loop. I think these changes should be sufficient, but I haven't run unit tests on it.

**Comment by jasonb5** [comment]
@forsyth2 The changes look good but lets get the unit tests ran against this for sanity sake. I'm working on the dev-environment so you can run unit tests locally, let me get that into master and you can update and run the tests.

**Comment by jasonb5** [comment]
@forsyth2 You can sync with master and use `make dev-environment` and `make run-tests`. Once that's done we can get this merged.

**Comment by muryanto1** [comment]
@forsyth2 @jasonb5 I just noticed line 77 and line 79 of the Makefile in master branch needs to be fixed.
https://github.com/CDAT/cdms/blob/master/Makefile#L77-L79 -  It should be "-c cdat/label/nightly -c conda-forge".

**Comment by jasonb5** [comment]
> @forsyth2 @jasonb5 I just noticed line 77 and line 79 of the Makefile in master branch needs to be fixed.
> https://github.com/CDAT/cdms/blob/master/Makefile#L77-L79 - It should be "-c cdat/label/nightly -c conda-forge".

@muryanto1 I think this is fine, the reason for it was in a dev environment i want to start with the latest released version of everything. If we want to change this behavior lets do another PR so we can get this merged and move on with 8.2.1.

**Comment by jasonb5** [comment]
Ok this looks good.

**Review by jasonb5 — APPROVED** [review]
LGTM

**Comment by forsyth2** [comment]
I managed to run the tests and got `Ran 55 tests, 0 failed (100.00% success)`. Jason also confirmed the original error (#397) is fixed by this.

**Pull request merged**
