### PR TITLE
Compute graph provenance [WIP]

### PR DESCRIPTION
**Pull request by chaosphere2112**
Going to have to finish this tomorrow as I don't have time today; this pull request requires the [UV-CDAT/compute_graph](https://github.com/UV-CDAT/compute_graph) library to be installed. I'll break it down a bit more tomorrow when wrapping everything up.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
Alright, this is in decent shape at this point. I'll provide an overview of what we've got here:

## compute_graph

`compute_graph` is a package I built to extract out the core of the provenance. It allows the creation of a directed acyclic graph that represents a piece of data analysis, and provides APIs to add additional pieces of functionality to it. The core package provides basic arithmetic and literal values; in CDMS, we add `dataset` access, `metadata` functions, some `geospatial` manipulations, and `ndarray` operations. These are located in the modules of the `cdms2.provenance.operations` package.

## Basic Use

At this point, there's no automatic construction of the graph, just the basic utilities to build the graph and derive values from a prebuilt graph. VCDAT is going to manually construct the graph and pass it to `vcs-js`, which will get us a good 90% of the way to where we need to be.

Here's a walkthrough of how to use it:

```python
from compute_graph import *
from cdms2.provenance import *

opendap = "http://test.opendap.org/dap/data/nc/sst.mnmean.nc.gz"

# Get the time axis first so we can just pick out a single time slice
time_axis = DatasetFunction(opendap, "axis", "time")
time_axis_first = NDArraySubsetFunction(time_axis, 0)

sst = DatasetFunction(opendap, "variable", "sst", time=time_axis_first, squeeze=True)

# Grab some lower latitudes for a subset
lat = GeospatialFunction("lat", sst)
lat_lower = NDArraySubsetFunction(lat, 0)
lat_upper = NDArraySubsetFunction(lat, 20)

subset_sst = GeospatialFunction("subset", arr, latitude=(lat_lower, lat_upper))

# Average across longitude
x_avg_subset_sst = NDArrayAxisFunction("average", subset_sst, axis=1)

# All done!
json = compute_graph.dumpjson(x_avg_subset_sst)
```

We can then take that JSON blob and reuse it later:

```python
import compute_graph
import cdms2.provenance
node = compute_graph.loadjson(json)
array = node.derive()
```

This will rebuild the tree using generic `ComputeNode`s, not the custom types used to build the tree originally, but everything will still work the same. You have to import `cdms2.provenance` in order for the computations to work; `compute_graph` uses a registration decorator to let the derivation code know how to handle a new kind of node not specified in the base system. The call to `node.derive()` returns the fully derived value of the computation specified in the JSON.

## Future work

I still need to do operations for `genutil` and `cdutil` to provide the full suite of analysis tools. `cdutil` will define a new domain (`climate`), and `genutil` will provide `stats` functions. That will have to happen outside this PR, since we don't want to nest circular dependencies here.

**Comment by durack1** [comment]
@chaosphere2112 this sounds cool, but reading the above I don't see what it would be practically useful for.. A demo of this would be great.. Potentially this could guide doc writing..

**Comment by chaosphere2112** [comment]
@durack1 It's not actually an end-user feature. This is intended to be used for serializing data analysis to pass to a compute server for HPC purposes.

**Comment by chaosphere2112** [comment]
@dnadeau4 After speaking with Dean yesterday, I think the way we're going to handle this will probably want to change. I'll move this code into a new repo (CDAT-compute or something like that) and we can add the `cdutil`/`genutil` support there.

If we make `cdutil` and `genutil` support optional in CDAT-compute, then we can eventually make CDMS dependent on the new package without adding nasty dependency cycles between our libraries.

I'm going to close this PR and get the new repo made before I leave.

**Pull request closed without merging**
