### PR TITLE
Numpy1 11

### PR DESCRIPTION
**Pull request by dnadeau4**
All ctest are passing with numpy 1.11

```
99% tests passed, 1 tests failed out of 654

Total Test time (real) = 237.29 sec

The following tests FAILED:
     39 - flake8_vcs (Failed)
Performing coverage
```

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 do you mind adding a `numpy1_11` branch on UV-CDAT/uvcdat which will trigger a build of this. Make sure it's using numpy 1.11 i.e points to your repo to download libcdms, etc... Don't worry about breaking `.travis.yml` we will probably not merge the branch in master. Just would like it to be triggered.

**Comment by dnadeau4** [comment]
might be hard to do,  I had to rebuild esmf and clapack with numpy 1.11

We'll see...

**Comment by doutriaux1** [comment]
butthey are on your channel right? You just need to tell it to look into your channel first.

**Comment by dnadeau4** [comment]
They are on my local machine now.  I will push on my personal channel.

Denis

**Comment by chaosphere2112** [comment]
@doutriaux1 @dnadeau4 This passes all of the tests that are passing from my test branch. I give it the big ol' :+1:

**Pull request merged**
