### PR TITLE
Issue32

### PR DESCRIPTION
**Pull request by dnadeau4**
isLatitude and isLongitude now verify that order axes verifications does not return true before accepting the variable as a axis.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 please add tests

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
we need tests

**Comment by durack1** [comment]
@dnadeau4 does this PR provide `string` support in `cdms2/CDUNIF`? Or is that another job in the queue?

**Comment by dnadeau4** [comment]
@durack1 That fixes your lat/lon issues when your units are reversed.

**Pull request merged**
