### PR TITLE
Periodicity dim

### PR DESCRIPTION
**Pull request by dnadeau4**
Add 2 parameters to ESMF.grid
* periodicity_dim
* pole_dim

Add test_periodicity.py

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 two failures now esmfmask and esmf3dsmallesmf

**Comment by dnadeau4** [comment]
@doutriaux1 please merge!

**Comment by chengzhuzhang** [comment]
Fixed the my periodicity problem. Tested for "liner" and "conservative", both worked. Thank you @dnadeau4

**Comment by dnadeau4** [comment]
Yeah!!

**Pull request merged**
