### PR TITLE
Issue 153 cross section

### LINKED ISSUE #153: Undefined local variable with regrid2.crossSection.get_latitude_wts_bnds
@chengzhuzhang Uncovered this error.

A quick glance at the `get_latitude_wts_bnds()` function shows that `wts` is only declared in the if statements, thus an error on the line `return (wts, bnds)`.
Maybe we need to initialize wts to None?

Your thoughts @dnadeau4 

```
Traceback (most recent call last):
  File "acme_diags_driver.py", line 79, in <module>
    run_diag(parameter)
  File "/Users/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/acme_diags-0.1-py2.7.egg/acme_diags/driver/zonal_mean_2d_driver.py", line 199, in run_diag
    mv1_reg = mv1_p.crossSectionRegrid(lev_out, lat_out)
  File "/Users/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/cdms2/avariable.py", line 1217, in crossSectionRegrid
    fromlat, newLatitude, fromlevel, newLevel)
  File "/Users/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/regrid2/crossSection.py", line 116, in __init__
    lat_wts_bndsIn = get_latitude_wts_bnds(latIn)
  File "/Users/zhang40/anaconda2/envs/acme_diags_env/lib/python2.7/site-packages/regrid2/crossSection.py", line 678, in get_latitude_wts_bnds
    return (wts, bnds)
UnboundLocalError: local variable 'wts' referenced before assignment
```

### PR DESCRIPTION
**Pull request by doutriaux1**
fix #153

### CODE REVIEW

**Comment by doutriaux1** [comment]
@zshaheen @chengzhuzhang  please review

**Comment by zshaheen** [comment]
@doutriaux1 

As per our Jabber conversation, here's how it looks like with the latest code on this PR.

screen shot 2017-08-09 at 10 08 04 am

**Comment by zshaheen** [comment]
@doutriaux1 
Also, running `cdutil.averager(diff, axis='yz', weights='generate')` to get the metrics breaks as well, only on the diff and not the reference or test.

**Comment by chengzhuzhang** [comment]
Great Job @doutriaux1 and @zshaheen !!

**Comment by doutriaux1** [comment]
screen shot 2017-08-09 at 10 46 43 am

**Pull request merged**
