### PR TITLE
Fixes int overflow when requesting large slices

### LINKED ISSUE #383: Problems with reading "big" arrays (>8.1Gb)
**Describe the bug**
I have hit a reproducible error where big arrays (>8.1Gb) are not read correctly, rather with a zero array (rather than real numbers) being returned. I was a little puzzled by this error, and got talking with @painter1 who also had this problem and reported it back via email in May 2019. It turns out that the issue is with arrays greater than 8.1Gb, with the original error a bug with libnetcdf versions for big variables (from @painter1's notes/emails). @dnadeau4 and @doutriaux1 may recall some of the specific details about this. I note I may not be using the latest versions of libraries below.

**To Reproduce**
1. Install CDAT with: `cdms2-3.1.4-py37ha6f5e91_3`, `libnetcdf-4.6.2-h303dfb8_1003`, `netcdf-fortran-4.4.5-h0789656_1004`
2. Execute the code attached (which reads larger and larger arrays)
3. Watch as some summary stats go from real numbers to 0's when the arrays being read are >8Gb, which for the demo below happens at year 1989 (3rd step of the loop) when 26 years of data are being read (with the model having a vert/horiz grid of 60 vertical levels, 384 lat, 320 lon).

**Expected behavior**
Big arrays should be read validly, returning non-zero arrays

**Desktop (please complete the following information):**
 - OS: RHEL7.x

The code to reproduce this:
```python
# imports
import sys
import cdat_info
import cdms2 as cdm
import numpy as np
from socket import gethostname

#%% Define function
def calcAve(var):
    print('type(var);',type(var),'; var.shape:',var.shape)
    # Start querying stat functions
    print('var.min():'.ljust(21),var.min())
    print('var.max():'.ljust(21),var.max())
    print('np.ma.mean(var.data):',np.ma.mean(var.data)) ; # Not mask aware
    # Problem transientVariable.mean() function
    #print('var.mean():'.ljust(21),var.mean())
    print('-----')

#%% Load subset of variable
f = ['/p/css03/esgf_publish/CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/Omon/so/gn/v20190308/so_Omon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc']
# Try building up arrays stepping in a single year
times = np.arange(1991,1984,-1)
print('host:',gethostname())
print('Python version:',sys.version)
print('cdat env:',sys.executable.split('/')[5])
print('cdat version:',cdat_info.version()[0])
print('*****')
for timeSlot in times:
    for filePath in f:
        fH = cdm.open(filePath)
        print('filePath:',filePath.split('/')[-1])
        # Loop through single years
        start = timeSlot ; end = 2014
        print('times:',start,end,'; total years:',(end-start)+1)
        d1 = fH('so',time=(str(start),str(end)))
        print("Array size: %d Mb" % ( (d1.size * d1.itemsize) / (1024*1024) ) )
        calcAve(d1)
        del(d1)
        fH.close()
    print('----- -----')
```

@pochedls @muryanto1 @downiec @jasonb5 @gabdulla @gleckler1 @lee1043 ping

### PR DESCRIPTION
**Pull request by jasonb5**
Fix for #383 

The large slice size (300, 60, 384, 320) was causing the variable holding the total number of elements to overflow. The variable was type `int`, whose max value is 2,147,483,647 and the request slice was 2,211,840,000, causing the overflow. I've changed the type to `unsigned long` which i dont forsee anyone reading that much data into memory anytime soon.

@muryanto1 How would you like to tackle writing a test for this?

### CODE REVIEW

**Review by muryanto1 — APPROVED** [review]

**Comment by durack1** [comment]
@jasonb5 @muryanto1 absolute champs, I'll take `nightly` for a test and let you know if I hit any ongoing problems.

For a test, I am not sure how we can get around having a huge (>8Gb) dataset to read?

**Comment by hyma68** [comment]
@jasonb5 @muryanto1 @durack1 
I just tested the nightly version on NERSC cori use the following command:

conda create -n nightly -c cdat/label/nightly -c conda-forge cdat python=3.6

I still got zero values when loading a large size array. My array size is (56623106, 137), which is 7,757,365,522. This should be within the "unsigned long" limit. Did I get the right nightly version?

**Comment by muryanto1** [comment]
@hyma68 Please do:
conda create -n cdms_nightly -c cdat/label/nightly -c conda-forge cdms2 python=3.7.
I only built for python 2.7 and python 3.7 https://anaconda.org/cdat/cdms2/files
I hope you can use python 3.7.

**Comment by hyma68** [comment]
@muryanto1 
Thanks! It is working now for loading large size array. I was able to do python 3.7. 
Another question, it seems I can't import "cdutil", and "genutil" with this build. Is there a quick solution that I can import other cdat modules including the two with this build? Thanks again.

**Comment by muryanto1** [comment]
@hyma68 If you need any other cdat packages, you can do:
conda install -n cdms_nightly -c cdat/label/nightly -c conda-forge cdutil genutil
and any other cdat packages you may need.

**Comment by durack1** [comment]
@muryanto1, if it's not complicated to implement, could this fix be rolled out for all nightlies? It would create more work for you guys to address continuing bug reports when turning on broader nightly builds could solve this long-standing issue

**Pull request merged**
