### PR TITLE
moved recipe in repo, added llnl required license file

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@dnadeau4 it does not seem related to my PR, do you know what is going on here?
```
======================================================================
ERROR: retrieve value from cdscan
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/tests/test_cdscan.py", line 63, in testopenFile
    cdscan(argv)
  File "/home/circleci/project/test_linux_cdms_py2/miniconda/envs/py2/lib/python2.7/site-packages/cdms2/cdscan.py", line 1075, in main
    raise RuntimeError('Error opening file ' + path)
RuntimeError: Error opening file https://dataserver.nccs.nasa.gov/thredds/dodsC/bypass/CREATE-IP/Reanalysis/NASA-GMAO/GEOS-5/MERRA/mon/atmos/zg.ncml
----------------------------------------------------------------------
Ran 2 tests in 0.303s
FAILED (errors=1)
```

**Comment by doutriaux1** [comment]
@dnadeau4 did we fix the dap issue?

**Comment by dnadeau4** [comment]
I fixed it in conda-forge.  I had to change the way the "mode" is passed to netcdf_open.

**Comment by doutriaux1** [comment]
so is it in master?

**Comment by doutriaux1** [comment]
can we close this one then?

**Comment by dnadeau4** [comment]
I did not create your soft link, I just add the license to conda-forge meta.yaml and add the `bsd` license to mater.

**Comment by dnadeau4** [comment]
Let see if the test passes

**Comment by doutriaux1** [comment]
thanks

**Pull request merged**
