### PR TITLE
Fixes error messages #409

### LINKED ISSUE #409: Simplify the error message, when opening a non existing nc file
Using cdms 3.0.0 of CDAT 8.1

The long traceback you get **when you try to open a non existing nc file** is a bit confusing. Is there a way to display a simple and straightforward _File not found_ error?

It's all the more confusing because the long traceback is not the same if you use python2 or python3! The python3 version adds a` OSError: Variable not found message`!

### Python2 case
```
>>> f = cdms2.open('not_found.nc')
CDMS system error: No such file or directory
CDMS I/O error: Opening file /home/scratch01/jypeter/cdms2_bug_data/not_found.nc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdms2/dataset.py", line 499, in openDataset
    return CdmsFile(path, mode, mpiBarrier=CdMpi)
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py2/lib/python2.7/site-packages/cdms2/dataset.py", line 1283, in __init__
    raise CDMSError('Cannot open file %s (%s)' % (path, err))
cdms2.error.CDMSError: Cannot open file /home/scratch01/jypeter/cdms2_bug_data/not_found.nc (No error)
>>>
```

### Python3 case
```
>>> f = cdms2.open('not_found.nc')
CDMS system error: No such file or directory
CDMS I/O error: Opening file /home/users/jypeter/CDAT/Progs/Devel/masa/PMIP4_Sandy/not_found.nc
Traceback (most recent call last):
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 1281, in __init__
    _fileobj_ = Cdunif.CdunifFile(path, mode)
OSError: Variable not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 499, in openDataset
    return CdmsFile(path, mode, mpiBarrier=CdMpi)
  File "/home/share/unix_files/cdat/miniconda3/envs/cdatm_py3/lib/python3.6/site-packages/cdms2/dataset.py", line 1283, in __init__
    raise CDMSError('Cannot open file %s (%s)' % (path, err))
cdms2.error.CDMSError: Cannot open file /home/users/jypeter/CDAT/Progs/Devel/masa/PMIP4_Sandy/not_found.nc (Variable not found)
```

### PR DESCRIPTION
**Pull request by jasonb5**
- Fixes opening non-existent files will now raise `FileNotFoundError`.
- Fixes `Cdunif.CdunfiError`.
- Fixes raising `CdunifError` in `Cdunif` module, previously this was an `OSError`, which made node sense.
- Fixes propagating errors from libcdms to `Cdunif` module, alot of errors would be raised as "No Error"
- Fixes nested errors when opening files. This would occur if something failed while opening a file and would result in both an `OSError` and `CDMSError` being raised, creating a very confusing stacktrace. This will now raise a `CdunifError`.

### CODE REVIEW

**Comment by muryanto1** [comment]
@jasonb5 Hi Jason, can you update last_stable to be 3.1.5 in the Makefile?

**Comment by jasonb5** [comment]
@muryanto1 sure thing, i'm not sure when i'll be ready to merge this. I need to figure something out for `CdunifError` as this is currently API breaking and i'd like to find a different solution.

**Comment by jasonb5** [comment]
I brought the `CDMSError` into the c layer so we could use it as a base for `CdunifError`. This should prevent breaking the API when raising the new `CdunifError` when `open` fails.

**Review by downiec — APPROVED** [review]
Looks good to me, but did you plan on leaving the commented out code in there for reference?

**Comment by jasonb5** [comment]
Ah good point, I should probably remove it.

**Pull request merged**
